#!/usr/bin/env bash
# Displays information about a file

file="filename"

if [ -e "$file" ]; then
	echo "$file" exists
	if [ -s "$file" ]; then
		echo "$file" is not empty
	else
		echo "$file" is empty
	fi
	if [ -f "$file" ]; then
		echo "$file" is regular
	fi
else
	echo "$file" does not exist
fi
