#!/usr/bin/env bash
# This script resolves:
#	localhost to 127.0.0.2
#	facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g ~/hosts.new
cat ~/hosts.new > /etc/hosts
